create table if not exists public.conversation_logs (
  id bigint generated by default as identity primary key,
  logged_at timestamptz not null default now(),
  call_sid text,
  conversation_id text,
  caller_phone text,
  source text,
  event text,
  webhook_type text,
  record jsonb not null
);

create index if not exists conversation_logs_logged_at_idx
  on public.conversation_logs (logged_at desc);
create index if not exists conversation_logs_call_sid_idx
  on public.conversation_logs (call_sid);
create index if not exists conversation_logs_conversation_id_idx
  on public.conversation_logs (conversation_id);

create table if not exists public.call_transcripts (
  id bigint generated by default as identity primary key,
  logged_at timestamptz not null default now(),
  call_sid text,
  conversation_id text,
  caller_phone text,
  source text,
  event text,
  transcript_snippet text,
  messages jsonb,
  update_count integer not null default 0,
  record jsonb not null
);

create index if not exists call_transcripts_logged_at_idx
  on public.call_transcripts (logged_at desc);
create index if not exists call_transcripts_call_sid_idx
  on public.call_transcripts (call_sid);
create index if not exists call_transcripts_conversation_id_idx
  on public.call_transcripts (conversation_id);
